### ISSUE TITLE
"round" counter really necessary

### ISSUE THREAD

**Issue by jpmeijers** [kiu/lofence#11]
LoRaWAN has a frame counter that also increments every transmission. Does the "round" counter really add any extra usefulinformation?

Currently this project uses ABP and the frame counter will not reset during a power cycle. One will therefore not see a restart in the frame counter, and this "round" counter might be useful.

I'm however of the opinion one should switch to OTAA. I'll file a PR for OTAA in the coming days.

**Comment by kiu** [comment]
I wanted to detect resets, not received uplinks and # of rounds per battery charge using the rounds mechanism.

**Comment by jpmeijers** [comment]
Yes makes sense. If we switch to OTAA and do an OTAA join at startup, you can do all that with the LoRaWAN FCnt. That will save 2 bytes of payload.

**Comment by kiu** [comment]
![image](https://user-images.githubusercontent.com/785968/137759047-b9a76f6d-d34a-4b8a-a111-82c8d6eae98d.png)

**Comment by jpmeijers** [comment]
![image](https://user-images.githubusercontent.com/948278/137761524-41faefbf-0b0e-478f-8d0a-5aba8e3d5760.png)

And then you can do a `difference()` on the FCnt value to get this graph on which you can set an alert if the value is <0.
![image](https://user-images.githubusercontent.com/948278/137761855-747375e3-3f4d-4254-9540-6b2dd8787431.png)
