### ISSUE TITLE
Impulse measurement

### ISSUE THREAD

**Issue by Inrebusillis** [kiu/lofence#14]
I have built the divider and the amp circuit and send the signal to a Dragino LSN50 V2 and V3 to make easy the LoRa part for me as I have this module from othes project,
everything working excellent BUT:
- the fence ( big bully up to 12kV is powered by voltage impulse ( about 30 ms)  every 0.8 seconds so Is not constantly all the time powered ( my unsterstand) 
- the LNS50 wake up take a measurement from the circuit and go sleep for the next 20 minutes

obviusly the probability that the impulse is done just when the module is awake is really low.

How can measure the voltage and "hold the value" ( measure the impulse) till the sending module is awake again?
Or I missing something ?
thanks

**Comment by jpmeijers** [comment]
Your understanding is correct.

Each time the Atmega 328p wakes up (every hour), the firmware samples the ADC for 15 seconds, at a rate of 250kHz, storing the max and min values it encounters. It will therefore measure more than 15 pulses in a row, storing the maximum sample, of the maximum pulse, and report that as the voltage.

You can have a look at how the ADC is set up here:
https://github.com/kiu/lofence/blob/9a1d09bd57b84be4a4ec193df7fd8c69c1f981a8/rev_b/firmware/LoFence/main.c#L52

**Comment by Inrebusillis** [comment]
so to built it I have to use the full project.
let me ask you: I have a friends/farmer that need to 7 of these,
I am already running a TTI network.
Can I use your project? which conditions?
I would like to have a short chat with you, could you send me your tel via PN?
Thanks

**Comment by Alex9779** [comment]
I tried the same about a year ago, I developed several iterations of a "sensor module" for connecting to an LSN50-V2 using just the divider and the opamp, one verison also used a smaller AVR MCU but I wasn't able to work reliable.
One problem is the spefic characteristics of the ADC of the ATmega 328PB of the original design.
The other is the firmware of the LSN50 which is not capable of "waiting" a defined time frame for a function running in the background to get the max value of several impulses. I mean to run the ADC in free running mode with interrupt like the LoFence firmware does, I wasn't able to do the same for the STM based LSN50.
I tried to program a new firmware using the ADC of the LSN50 itself but didn't succeed.

ATM I am finalizing a V2 version with a smaller case, a different LoRa module and two 18650 or 18500 batteries, that is not fixed yet...

**Comment by Alex9779** [comment]
This is how one version looked like:
![66585304621__CCD708C8-54C3-49F1-8988-686080E2FB1A](https://github.com/kiu/lofence/assets/6394581/e665e243-8754-4572-81e7-2cb46aa0eb84)

And this how my current design looks like:
![LoFence-V2](https://github.com/kiu/lofence/assets/6394581/8d2978a3-c4e5-4b3c-9e53-02e3ca32d7d8)

**Comment by Alex9779** [comment]
> How can measure the voltage and "hold the value" ( measure the impulse) till the sending module is awake again?

This is the problem, to "store" the voltage longer you need bigger capacitors, but bigger caps need more current to fill, if they are too big your fence won't work or your fnece charger will go to error, because usually voltage is high and current is very low. So the more current you use to measure the more is missing on the fence.
This seems to be very balanced in the original LoFence design.
All the opamp circuit is to "store" the maximum voltage of the peak a little longer but still this voltage drops fast.
So in my tries to measure that stored voltage with the LSN50 I always had the problem that the ADC didn't measure to the right time. The correct method to do it is like the original firmware does, let the ADC run free, when it has measured then use the interrupt to compare to a previous stored value and if the new is bigger store that and do all this for some time, I do it for about 3-4 peaks of my fence.
I wasn't able to program this into the LSN50 firmware so I had to discontinue because at least for me it was not solvable.

**Comment by Inrebusillis** [comment]
Thanks!
Your design with two cases look familiar to me 😉

Happy to know that I am not alone.
that is exacly the point where I am right now.

I am in a classic buy or build decision:
- Getting the grant to commercialize the original Project „as it is“
- build a Firmware that enable  the LNS50 to do the missing bit….( may be I could konw someone able to do it….
Thanks and regards
Gilberto





Gesendet von Mail für Windows

Von: Alexander Leisentritt
Gesendet: Dienstag, 19. September 2023 17:32
An: kiu/lofence
Cc: Inrebusillis; Author
Betreff: Re: [kiu/lofence] Impulse measurement (Issue #14)

How can measure the voltage and "hold the value" ( measure the impulse) till the sending module is awake again?
This is the problem, to "store" the voltage longer you need bigger capacitors, but bigger caps need more current to fill, if they are too big your fence won't work or your fnece charger will go to error, because usually voltage is high and current is very low. So the more current you use to measure the more is missing on the fence.
This seems to be very balanced in the original LoFence design.
All the opamp circuit is to "store" the maximum voltage of the peak a little longer but still this voltage drops fast.
So in my tries to measure that stored voltage with the LSN50 I always had the problem that the ADC didn't measure to the right time. The correct method to do it is like the original firmware does, let the ADC run free, when it has measured then use the interrupt to compare to a previous stored value and if the new is bigger store that and do all this for some time, I do it for about 3-4 peaks of my fence.
I wasn't able to program this into the LSN50 firmware so I had to discontinue because at least for me it was not solvable.

**Comment by Alex9779** [comment]
One thing to consider is that the circuit with the OpAmp to "store" the peak and let the LSN ADC measure that is that it also uses current and from what I calculated the LSN battery would last about 2 years when measuring every 5 minutes like I do now.
And that battery is not chargeable.
This was something I wanted to accept and which also would lead to some money each year or two to keep it running...
In the end I chose to redesign the original device to have more lifetime, not to deep discharge the batteries when they run low and I dont change then right away and a different case which can be opened without dismounting it every time...

**Comment by Alex9779** [comment]
@Inrebusillis Tried to send you a mail on your homepage, no idea if that worked, contact me by mail if you want to talk, think you are in  Germany too...

**Comment by Inrebusillis** [comment]
thx, 
sent you a mail

**Comment by Inrebusillis** [comment]
thanks,[jpmeijers](https://github.com/jpmeijers) you nailed it.
Each time the Atmega 328p wakes up (every hour), the firmware samples the ADC for 15 seconds, at a rate of 250kHz, storing the max and min values it encounters. It will therefore measure more than 15 pulses in a row, storing the maximum sample, of the maximum pulse, and report that as the voltage.
