### ISSUE TITLE
missing symbols

### ISSUE THREAD

**Issue by toozie21** [kiu/lofence#2]
Nice design!

I am new to KiCad and when I opened your project there were missing symbols for the schematic (like for the RN2483).  Are those symbols something that you drew by hand? I haven't looked at the PCB yet, but I will let you know if I see similar issues there.

**Comment by kiu** [comment]
Uh, thanks for pointing that out. I accidentally gitignored the cache.lib file.
Please update and check again.

**Comment by toozie21** [comment]
> Uh, thanks for pointing that out. I accidentally gitignored the cache.lib file.
> Please update and check again.

Thank you, that did solve that issue.  Though it seemed to cause a different one after I updated...
![Screenshot from 2020-07-23 15-41-45](https://user-images.githubusercontent.com/6740294/88331759-7af5ad00-ccfb-11ea-943a-cd3d5fe9c7d2.png)

**Comment by kiu** [comment]
Odd. I did a clean install of kicad on a machine where I never used kicad on before. Did a git clone and get no errors. I do get a wizard though, but that works fine.

![Image Pasted at 2020-7-23 23-01](https://user-images.githubusercontent.com/785968/88338521-c11d3180-cd38-11ea-84ea-287a9f8ba89f.jpg)

**Comment by toozie21** [comment]
Weird. What version of KiCad?

**Comment by kiu** [comment]
I installed latest stable 64bit Windows Version, that is 5.1.6
https://kicad-pcb.org/download/windows/

**Comment by toozie21** [comment]
> I installed latest stable 64bit Windows Version, that is 5.1.6
> https://kicad-pcb.org/download/windows/

I was using Ubuntu and it was one minor version behind.  I installed it on my Windows laptop to make it easier and it seemed to load up fine, so I think you solved the problem, thanks!!
