### ISSUE TITLE
R5, R6 BOM order number wrong

### ISSUE THREAD

**Issue by Alex9779** [kiu/lofence#5]
R5 and R6 in the BOM have a 0805 footprint but the Mouser part number resolves to resistors with a 1206 case.
Think it is just a typo because there exists pretty much the same resistors in 0805 with order number 660-RK73H2**A**TTD2320F instead of 660-RK73H2**B**TTD2320F.

**Comment by kiu** [comment]
Good catch!
https://github.com/kiu/lofence/commit/79e2fb9587586af6832cf9452c6af343f834de3f
