### ISSUE TITLE
op-amp power supply

### ISSUE THREAD

**Issue by 4Inno** [kiu/lofence#8]
Hey there,
great project! Isn't the op-amp missing the supply power? ADC_POWER is only conntected to the uC. Or am I missing something?
Best regards

**Comment by kiu** [comment]
The ADC_POWER is directly powering the opamp from the uC everytime a measuring cycle is run. That way the op-amp does not consume any power when its not needed as the uC can turn it off.

**Comment by 4Inno** [comment]
Thank you! I will close the issue.
